-- SPDX-FileCopyrightText: 2021 Arthur Breitman
-- SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

module Test.SegCFMM.Storage
  ( defaultStorage
  , storageWithIncreasedBuffer10
  , storageWithMetadata
  ) where

import Michelson.Typed

import SegCFMM.Types
import Util (fetchValue)

defaultStorage :: Storage
defaultStorage =
  fromVal ($(fetchValue @Storage "test/storage_default.tz"))

storageWithIncreasedBuffer10 :: Storage
storageWithIncreasedBuffer10 =
  fromVal ($(fetchValue @Storage "test/storage_increased_buffer_10.tz"))

-- | Generated by:
-- make out/metadata_map
-- make out/storage_default.tz \
--   fee_bps=10 \
--   ctez_burn_fee_bps=5 \
--   x_token_id=0 \
--   y_token_id=0 \
--   x_token_address=KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn \
--   y_token_address=KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn \
--   tick_spacing=1 \
--   init_cumulatives_buffer_extra_slots=0 \
--   metadata_map="$(cat out/metadata_map)"
storageWithMetadata :: Storage
storageWithMetadata =
  fromVal ($(fetchValue @Storage "test/assets/storage_with_metadata.tz"))
